### ISSUE TITLE
Rename episode md files to not carry a number

### ISSUE THREAD

**Issue by bast** [coderefinery/testing#85]
Before sending the PR, good idea or bad idea?

**Comment by bast** [comment]
@rkdarst

**Comment by rkdarst** [comment]
I don't see why not, it is what I would do by default.  I guess it changes URLs from previous iterations, but that's probably OK.

Lately I have noticed it's nice to see the number in the screen-sharers URL bar, so that I can find the right episode quickly.  But, I think that's really minor, and these days we don't even expose the numbers so it's not really relevant.

+1 to do the change.
